SECTION_ALIASES = {
    "profile": {
        "about",
        "about me",
        "career objective",
        "objective",
        "personal profile",
        "profile",
        "professional summary",
        "profil",
        "ringkasan",
        "summary",
        "tentang saya",
    },
    "education": {
        "academic background",
        "education",
        "educational background",
        "pendidikan",
        "riwayat pendidikan",
    },
    "experience": {
        "employment",
        "employment history",
        "experience",
        "internship",
        "magang",
        "pengalaman",
        "pengalaman kerja",
        "project",
        "projects",
        "proyek",
        "work experience",
        "work history",
    },
    "skills": {
        "competencies",
        "competency",
        "kemampuan",
        "keahlian",
        "skills",
        "technical skills",
        "tools",
    },
    "certification": {
        "certificate",
        "certification",
        "certifications",
        "lisensi",
        "sertifikasi",
    },
}

BILINGUAL_SKILL_ALIASES = {
    "api": {"api", "graphql", "rest", "rest api", "restful", "webhook"},
    "communication": {"communication", "komunikasi", "presentasi", "presentation"},
    "data_analysis": {
        "analisis data",
        "analytics",
        "data analysis",
        "data analytics",
        "olah data",
        "pengolahan data",
    },
    "database": {"database", "basis data", "mongodb", "mysql", "postgres", "postgresql", "redis", "sql"},
    "docker": {"container", "containerization", "docker", "docker compose", "kontainer"},
    "figma": {"figma", "prototype", "prototipe", "wireframe"},
    "flutter": {"dart", "flutter"},
    "laravel": {"laravel", "php laravel"},
    "leadership": {"kepemimpinan", "leadership", "lead team", "memimpin", "team lead"},
    "machine_learning": {
        "ai",
        "artificial intelligence",
        "kecerdasan buatan",
        "machine learning",
        "ml",
        "pembelajaran mesin",
    },
    "marketing": {"campaign", "digital marketing", "kampanye", "marketing", "pemasaran"},
    "mobile_development": {"android", "ios", "mobile", "mobile development", "pengembangan mobile"},
    "nodejs": {"express", "node", "node.js", "nodejs"},
    "php": {"codeigniter", "php", "symfony"},
    "python": {"django", "fastapi", "flask", "python"},
    "react": {"next.js", "nextjs", "react", "react.js", "reactjs"},
    "teamwork": {"collaboration", "kolaborasi", "kerja sama", "teamwork"},
    "testing": {"jest", "phpunit", "pytest", "qa", "quality assurance", "testing", "unit test"},
    "ui_ux": {"ui", "ui/ux", "user experience", "user interface", "ux"},
}

ROLE_ALIASES = {
    "accounting_staff": {"accounting staff", "finance staff", "staf akuntansi", "staf keuangan"},
    "backend_developer": {"backend developer", "backend engineer", "programmer backend"},
    "data_analyst": {"analis data", "data analyst"},
    "digital_marketer": {"digital marketer", "social media specialist", "spesialis media sosial"},
    "frontend_developer": {"frontend developer", "frontend engineer", "programmer frontend"},
    "software_engineer": {"developer", "programmer", "software engineer", "software engineer intern"},
    "ui_ux_designer": {"product designer", "ui designer", "ui/ux designer", "ux designer"},
}

ACTION_VERBS_BILINGUAL = {
    "achieved",
    "built",
    "created",
    "designed",
    "developed",
    "improved",
    "implemented",
    "launched",
    "managed",
    "membangun",
    "membuat",
    "mengembangkan",
    "mengelola",
    "mengimplementasikan",
    "meningkatkan",
    "merancang",
    "optimized",
}
